version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: willson_fuzzy_approximation
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local
    ports:
      - "8888:8888"
    command: /start

